kind: Secret
apiVersion: v1
metadata:
  name: mongodb-creds
  namespace: emart
type: Opaque
data:
  password: YWRtaW4xMjMNCg==    # admin123
  username: cm9vdA0K            # root

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: emart
type: Opaque
data:
  mysql-pass: YWRtaW4xMjMNCg==        # admin123
  mysql-user: YWRtaW4=                # admin
  mysql-user-pass: YWRtaW4xMjMNCg==        # admin123
  #rmq-pass: Z3Vlc3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
  namespace: emart
data:
  # Configuration values can be set as key-value properties
  mongodbname: "epoc"
  mongo_uri: "mongodb://mongodb:27017/epoc"
  mysqldbname: "books"
