apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: wordpress
type: Opaque
data:
  mysql-pass: YWRtaW4xMjMNCg==  # admin123
  mysql-user: YWRtaW4=          # admin 
  mysql-user-pass: YWRtaW4xMjMNCg==        # admin123
  #rmq-pass: Z3Vlc3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
  namespace: wordpress
data:
  # Configuration values can be set as key-value properties

  mysqldbname: "wordpress"
